import Card from "@/components/Card";
import Landing from "@/components/Landing";
import Head from "next/head";
import { gql, GraphQLClient } from "graphql-request";

interface Props {
  posts: Posts[];
}

export default function Home({ posts }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[calc(100vh_-_64px)] snap-y overflow-y-scroll scrollbar-hide">
        <Landing />
        <Card posts={posts} />
        {/* footer */}
      </main>
    </>
  );
}

const QUERY = gql`
  {
    posts {
      title
      datePublished
      slug
      content {
        html
      }
      coverPhoto {
        url
      }
      author {
        name
        avatar {
          url
        }
        jobTitle
        about
      }
    }
  }
`;

const client = new GraphQLClient(
  "https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/clg0ry71v7uga01uie2yhanbv/master"
);

export async function getStaticProps() {
  const { posts }: any = await client.request(QUERY);
  return {
    props: {
      posts,
    },
  };
}
